package image_test

import (
	"strings"
	"testing"

	image "github.com/harveysanders/advent-of-code-2023/day11-cosmic-expansion"
	"github.com/stretchr/testify/require"
)

func TestExpand(t *testing.T) {
	sample := strings.NewReader(`...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....
`)

	wantExpanded := `....#........
.........#...
#............
.............
.............
........#....
.#...........
............#
.............
.............
.........#...
#....#.......
`

	observation, err := image.ParseImage(sample)
	require.NoError(t, err)

	expanded := observation.Expand()
	// require.Equal(t, 13, expanded.Width())
	require.Equal(t, 12, expanded.Height())

	got := expanded.String()
	require.Equal(t, wantExpanded, got+"\n")
}
